// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpbzdPqvcakGw0jDVoAiSJpLGqne_8Grs',
    appId: '1:1071948058520:web:5e53a5a171ed2be26ee5ed',
    messagingSenderId: '1071948058520',
    projectId: 'homefirebase-bde6b',
    authDomain: 'homefirebase-bde6b.firebaseapp.com',
    storageBucket: 'homefirebase-bde6b.appspot.com',
    measurementId: 'G-Z8X2WE363C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1fIBQEnWK8U1QI-jJb1SB17loQ0LNdDU',
    appId: '1:1071948058520:android:c076fb602fa2a14e6ee5ed',
    messagingSenderId: '1071948058520',
    projectId: 'homefirebase-bde6b',
    storageBucket: 'homefirebase-bde6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmY4Zb43cID_Uwg-z20ra-H1myaJiwGbY',
    appId: '1:1071948058520:ios:4f7143a8677e5b6a6ee5ed',
    messagingSenderId: '1071948058520',
    projectId: 'homefirebase-bde6b',
    storageBucket: 'homefirebase-bde6b.appspot.com',
    iosBundleId: 'com.example.salesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmY4Zb43cID_Uwg-z20ra-H1myaJiwGbY',
    appId: '1:1071948058520:ios:c02a7b3f147e3e126ee5ed',
    messagingSenderId: '1071948058520',
    projectId: 'homefirebase-bde6b',
    storageBucket: 'homefirebase-bde6b.appspot.com',
    iosBundleId: 'com.example.salesApp.RunnerTests',
  );
}
